# Generated by Django 4.1.5 on 2023-01-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzitoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions_database1',
            name='researcher_name',
            field=models.CharField(default='De-miz', max_length=120, verbose_name='Your Name'),
        ),
    ]
