# Generated by Django 4.1.5 on 2023-01-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzitoapp', '0002_questions_database1_researcher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_database1',
            name='researcher_name',
            field=models.CharField(default='', max_length=120, verbose_name='Your Name'),
        ),
    ]
