# Generated by Django 4.1.5 on 2023-01-14 15:10

from django.db import migrations, models
import quizzitoapp.validations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzitoapp', '0004_alter_questions_database1_researcher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_database1',
            name='course',
            field=models.CharField(max_length=100, validators=[quizzitoapp.validations.to_lowercase]),
        ),
    ]
