# Generated by Django 4.1.5 on 2023-01-15 23:06

from django.db import migrations, models
import quizzitoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzitoapp', '0006_alter_questions_database1_researcher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_database1',
            name='question',
            field=models.TextField(validators=[quizzitoapp.models.duplicateDetector]),
        ),
    ]
