# Generated by Django 4.1.5 on 2023-01-18 01:32

from django.db import migrations, models
import quizzitoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzitoapp', '0007_alter_questions_database1_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_database1',
            name='answer',
            field=models.TextField(validators=[quizzitoapp.models.opt1_validation]),
        ),
        migrations.AlterField(
            model_name='questions_database1',
            name='option1',
            field=models.TextField(validators=[quizzitoapp.models.opt2_validation]),
        ),
        migrations.AlterField(
            model_name='questions_database1',
            name='option2',
            field=models.TextField(validators=[quizzitoapp.models.opt3_validation]),
        ),
        migrations.AlterField(
            model_name='questions_database1',
            name='option3',
            field=models.TextField(validators=[quizzitoapp.models.opt4_validation]),
        ),
    ]
