# Generated by Django 4.1.5 on 2023-03-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzitoapp', '0008_alter_questions_database1_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200, unique=True)),
            ],
        ),
    ]
