# Generated by Django 4.1.5 on 2023-03-24 21:48

from django.db import migrations, models
import quizzitoapp.validations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzitoapp', '0009_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_database1',
            name='researcher_name',
            field=models.CharField(default='demiz', max_length=120, validators=[quizzitoapp.validations.to_lowercase], verbose_name='Your Name'),
        ),
    ]
